

#include "null_platform.h"

#if defined(WSI_WIN32)
 #include "win32_platform.h"
 #define WSI_EXPOSE_NATIVE_WIN32
#else
 #define WSI_WIN32_WINDOW_STATE
 #define WSI_WIN32_MONITOR_STATE
 #define WSI_WIN32_CURSOR_STATE
 #define WSI_WIN32_LIBRARY_WINDOW_STATE
#endif

#if defined(WSI_COCOA)
 #include "cocoa_platform.h"
 #define WSI_EXPOSE_NATIVE_COCOA
#else
 #define WSI_COCOA_WINDOW_STATE
 #define WSI_COCOA_MONITOR_STATE
 #define WSI_COCOA_CURSOR_STATE
 #define WSI_COCOA_LIBRARY_WINDOW_STATE
#endif

#if defined(WSI_IOS)
 #include "uikit_platform.h"
 #define WSI_EXPOSE_NATIVE_IOS
#else
 #define WSI_IOS_WINDOW_STATE
 #define WSI_IOS_MONITOR_STATE
 #define WSI_IOS_CURSOR_STATE
 #define WSI_IOS_LIBRARY_WINDOW_STATE
#endif

#if defined(WSI_ANDROID)
 #include "android_platform.h"
 #define WSI_EXPOSE_NATIVE_ANDROID
#else
 #define WSI_ANDROID_WINDOW_STATE
 #define WSI_ANDROID_MONITOR_STATE
 #define WSI_ANDROID_CURSOR_STATE
 #define WSI_ANDROID_LIBRARY_WINDOW_STATE
#endif

#if defined(WSI_WAYLAND)
 #include "wl_platform.h"
 #define WSI_EXPOSE_NATIVE_WAYLAND
#else
 #define WSI_WAYLAND_WINDOW_STATE
 #define WSI_WAYLAND_MONITOR_STATE
 #define WSI_WAYLAND_CURSOR_STATE
 #define WSI_WAYLAND_LIBRARY_WINDOW_STATE
#endif

#if defined(WSI_X11)
 #include "x11_platform.h"
 #define WSI_EXPOSE_NATIVE_X11
#else
 #define WSI_X11_WINDOW_STATE
 #define WSI_X11_MONITOR_STATE
 #define WSI_X11_CURSOR_STATE
 #define WSI_X11_LIBRARY_WINDOW_STATE
#endif

#define WSI_PLATFORM_WINDOW_STATE \
        WSI_WIN32_WINDOW_STATE \
        WSI_COCOA_WINDOW_STATE \
        WSI_IOS_WINDOW_STATE \
        WSI_ANDROID_WINDOW_STATE \
        WSI_WAYLAND_WINDOW_STATE \
        WSI_X11_WINDOW_STATE \
        WSI_NULL_WINDOW_STATE \

#define WSI_PLATFORM_MONITOR_STAT \
        WSI_WIN32_MONITOR_STATE \
        WSI_COCOA_MONITOR_STATE \
        WSI_IOS_MONITOR_STATE \
        WSI_ANDROID_MONITOR_STATE \
        WSI_WAYLAND_MONITOR_STATE \
        WSI_X11_MONITOR_STATE \
        WSI_NULL_MONITOR_STATE \

#define WSI_PLATFORM_CURSOR_STATE \
        WSI_WIN32_CURSOR_STATE \
        WSI_COCOA_CURSOR_STATE \
        WSI_IOS_CURSOR_STATE \
        WSI_ANDROID_CURSOR_STATE \
        WSI_WAYLAND_CURSOR_STATE \
        WSI_X11_CURSOR_STATE \
        WSI_NULL_CURSOR_STATE \


#define WSI_PLATFORM_LIBRARY_WINDOW_STATE \
        WSI_WIN32_LIBRARY_WINDOW_STATE \
        WSI_COCOA_LIBRARY_WINDOW_STATE \
        WSI_IOS_LIBRARY_WINDOW_STATE \
        WSI_ANDROID_LIBRARY_WINDOW_STATE \
        WSI_WAYLAND_LIBRARY_WINDOW_STATE \
        WSI_X11_LIBRARY_WINDOW_STATE \
        WSI_NULL_LIBRARY_WINDOW_STATE \


#define WSI_PLATFORM_LIBRARY_CONTEXT_STATE

#if defined(WSI_WAYLAND) || defined(WSI_X11)
 #include "posix_poll.h"
 #define WSI_BUILD_POSIX_POLL
#endif

