# 由 scc --emit-sc 从 AST 再生成

inc ts.sc

fnc main: i4
    var shp[2]: i4
    shp[0] = 2
    shp[1] = 3
    var a: tensor& = zeros(2, shp, DT_F4)
    a->fill(2.0)
    printf("a numel=%lld sum=%g\n", a->numel, a->sum_all())
    var b: tensor& = arange(0.0, 6.0, 1.0, DT_F8)
    var b2: tensor& = b->reshape(2, shp)
    printf("b2 dim0=%d dim1=%d at5=%g dtype=%d contig=%d\n", b2->dim(0), b2->dim(1), b2->at(5), b2->dtype, (b2->is_contiguous(): i4))
    var c: tensor& = a->add(b2)
    printf("c sum=%g\n", c->sum_all())
    var rsh[2]: i4
    rsh[0] = 1
    rsh[1] = 3
    var row: tensor& = ones(2, rsh, DT_F8)
    var bc: tensor& = b2->add(row)
    printf("bc at0=%g at5=%g\n", bc->at(0), bc->at(5))
    var sh32[2]: i4
    sh32[0] = 3
    sh32[1] = 2
    var d: tensor& = ones(2, sh32, DT_F8)
    var mm: tensor& = b2->matmul(d)
    printf("mm shape=%dx%d at0=%g at3=%g\n", mm->dim(0), mm->dim(1), mm->at(0), mm->at(3))
    var sm: tensor& = b2->sum(1, false)
    printf("rowsum0=%g rowsum1=%g ndim=%d\n", sm->at(0), sm->at(1), sm->ndim)
    var mn: tensor& = b2->mean(1, true)
    printf("mean ndim=%d dim1=%d at0=%g at1=%g\n", mn->ndim, mn->dim(1), mn->at(0), mn->at(1))
    var am: tensor& = b->argmax(-1, false)
    printf("argmax=%g amdtype=%d\n", am->at(0), am->dtype)
    var ng: tensor& = b->neg()
    var rl: tensor& = ng->relu()
    printf("relu sum=%g\n", rl->sum_all())
    var t: tensor& = b2->transpose()
    printf("t shape=%dx%d at0=%g at5=%g contig=%d\n", t->dim(0), t->dim(1), t->at(0), t->at(5), (t->is_contiguous(): i4))
    var tc: tensor& = t->contiguous()
    printf("tc contig=%d at1=%g\n", (tc->is_contiguous(): i4), tc->at(1))
    var ey: tensor& = eye(3, DT_F4)
    printf("eye sum=%g diag4=%g\n", ey->sum_all(), ey->at(4))
    var ls: tensor& = linspace(0.0 - 2.0, 2.0, 5, DT_F8)
    var ab: tensor& = ls->abs()
    var cl: tensor& = ls->clip(0.0 - 1.0, 1.0)
    printf("ls at0=%g at4=%g abs at0=%g clip at0=%g at4=%g\n", ls->at(0), ls->at(4), ab->at(0), cl->at(0), cl->at(4))
    var gt: tensor& = b2->gt(a)
    printf("gt dtype=%d sum=%g\n", gt->dtype, gt->sum_all())
    var wh: tensor& = where(gt, b2, a)
    printf("where at0=%g at5=%g\n", wh->at(0), wh->at(5))
    var sl: tensor& = b->slice(0, 1, 5, 2)
    printf("slice numel=%lld at0=%g at1=%g\n", sl->numel, sl->at(0), sl->at(1))
    var r0: tensor& = b2->select(0, 0)
    printf("select ndim=%d at0=%g at2=%g\n", r0->ndim, r0->at(0), r0->at(2))
    var fl: tensor& = b->flip(0)
    printf("flip at0=%g at5=%g\n", fl->at(0), fl->at(5))
    var cs: tensor& = b->cumsum(0)
    printf("cumsum at0=%g at5=%g\n", cs->at(0), cs->at(5))
    var dp: f8 = b->dot(b)
    var ou: tensor& = sm->outer(sm)
    printf("dot=%g outer dim0=%d dim1=%d at0=%g\n", dp, ou->dim(0), ou->dim(1), ou->at(0))
    var pair[2]: &
    pair[0] = (a: &)
    pair[1] = (b2: &)
    var cat: tensor& = concat((pair: &), 2, 0)
    printf("concat dim0=%d dim1=%d numel=%lld\n", cat->dim(0), cat->dim(1), cat->numel)
    var nz: tensor& = b2->nonzero()
    printf("nonzero dim0=%d dim1=%d dtype=%d\n", nz->dim(0), nz->dim(1), nz->dtype)
    var gidx[2]: i4
    gidx[0] = 2
    gidx[1] = 2
    var gi: tensor& = zeros(2, gidx, DT_I8)
    gi->set_at(0, 0.0)
    gi->set_at(1, 2.0)
    gi->set_at(2, 1.0)
    gi->set_at(3, 0.0)
    var go: tensor& = b2->gather(1, gi)
    printf("gather at0=%g at1=%g at2=%g at3=%g\n", go->at(0), go->at(1), go->at(2), go->at(3))
    var sc0: tensor& = zeros(2, shp, DT_F8)
    var ssrc: tensor& = ones(2, gidx, DT_F8)
    var sc0r: bool = sc0->scatter_(1, gi, ssrc)
    printf("scatter_ ok=%d at0=%g at2=%g\n", (sc0r: i4), sc0->at(0), sc0->at(2))
    var pds[4]: i4
    pds[0] = 1
    pds[1] = 0
    pds[2] = 0
    pds[3] = 1
    var pd: tensor& = b2->pad(pds, 0.0 - 1.0)
    printf("pad dim0=%d dim1=%d at0=%g\n", pd->dim(0), pd->dim(1), pd->at(0))
    var ro: tensor& = b->roll(1, 0)
    printf("roll at0=%g at5=%g\n", ro->at(0), ro->at(5))
    var lsm: tensor& = b2->log_softmax(1)
    printf("log_softmax ndim=%d at2=%g\n", lsm->ndim, lsm->at(2))
    var lr: tensor& = ng->leaky_relu(0.1)
    var gl: tensor& = b->gelu()
    printf("leaky at0=%g gelu at5=%g\n", lr->at(0), gl->at(5))
    var tgt: tensor& = zeros(1, shp, DT_I8)
    tgt->set_at(0, 2.0)
    tgt->set_at(1, 0.0)
    var ce: f8 = b2->cross_entropy(tgt)
    printf("cross_entropy=%.4f\n", ce)
    var mset: tensor& = ones(2, shp, DT_F8)
    var mse: f8 = b2->mse_loss(mset)
    var nll: f8 = lsm->nll_loss(tgt)
    var bct: tensor& = zeros(2, shp, DT_F8)
    bct->set_at(1, 1.0)
    bct->set_at(3, 1.0)
    bct->set_at(5, 1.0)
    var bce: f8 = b2->bce_with_logits(bct)
    printf("mse=%.4f nll=%.4f bce=%.4f\n", mse, nll, bce)
    var ln: tensor& = b2->layer_norm(1, 0.00001)
    rand_seed(7)
    var dr: tensor& = b2->dropout(0.5, true)
    var dr_eval: tensor& = b2->dropout(0.5, false)
    printf("layer_norm at2=%.4f at5=%.4f dropout sum=%.4f eval_eq=%d\n", ln->at(2), ln->at(5), dr->sum_all(), (dr_eval->allclose(b2, 0.000001, 0.000001): i4))
    var sn: tensor& = b->sin()
    var cn: tensor& = b->cos()
    printf("sin at1=%.4f cos at0=%.4f\n", sn->at(1), cn->at(0))
    var a2: tensor& = b2->atan2(a)
    printf("atan2 at0=%.4f\n", a2->at(0))
    printf("median_all=%g pct50=%g\n", b->median_all(), b->percentile_all(50.0))
    var tu: tensor& = b2->triu(0)
    var tl: tensor& = b2->tril(0)
    printf("triu at1=%g at3=%g tril at1=%g at3=%g\n", tu->at(1), tu->at(3), tl->at(1), tl->at(3))
    var s22[2]: i4
    s22[0] = 2
    s22[1] = 2
    var M: tensor& = zeros(2, s22, DT_F8)
    M->set_at(0, 4.0)
    M->set_at(1, 1.0)
    M->set_at(2, 1.0)
    M->set_at(3, 3.0)
    printf("det=%.4f norm=%.4f\n", M->det(), M->norm(2.0))
    var Mi: tensor& = M->inv()
    printf("inv at0=%.4f at3=%.4f\n", Mi->at(0), Mi->at(3))
    var bb: tensor& = zeros(1, s22, DT_F8)
    bb->set_at(0, 1.0)
    bb->set_at(1, 2.0)
    var xx: tensor& = M->solve(bb)
    printf("solve at0=%.4f at1=%.4f\n", xx->at(0), xx->at(1))
    var Lc: tensor& = M->cholesky()
    printf("chol at0=%.4f at2=%.4f at3=%.4f\n", Lc->at(0), Lc->at(2), Lc->at(3))
    var eout[2]: &
    var eok: bool = M->eigh((eout: &))
    var evals: tensor& = (eout[0]: tensor&)
    var evecs: tensor& = (eout[1]: tensor&)
    printf("eigh ok=%d lo=%.4f hi=%.4f\n", (eok: i4), evals->at(0), evals->at(1))
    var qout[2]: &
    var qok: bool = M->qr((qout: &))
    var Qm: tensor& = (qout[0]: tensor&)
    var Rm: tensor& = (qout[1]: tensor&)
    printf("qr ok=%d R00=%.4f R11=%.4f\n", (qok: i4), Rm->at(0), Rm->at(3))
    var bu: tensor& = b2->unsqueeze(0)
    var du: tensor& = d->unsqueeze(0)
    var bm: tensor& = bu->bmm(du)
    printf("bmm dim0=%d dim1=%d dim2=%d at3=%g\n", bm->dim(0), bm->dim(1), bm->dim(2), bm->at(3))
    var ones22: tensor& = ones(2, s22, DT_F8)
    var adm: tensor& = ones22->addmm(M, Mi, 1.0, 1.0)
    printf("addmm at0=%.4f at1=%.4f at3=%.4f\n", adm->at(0), adm->at(1), adm->at(3))
    var s12[3]: i4
    s12[0] = 1
    s12[1] = 2
    s12[2] = 2
    var q3: tensor& = zeros(3, s12, DT_F8)
    q3->set_at(0, 1.0)
    q3->set_at(3, 1.0)
    var k3: tensor& = zeros(3, s12, DT_F8)
    k3->set_at(0, 1.0)
    k3->set_at(3, 1.0)
    var v3: tensor& = zeros(3, s12, DT_F8)
    v3->set_at(0, 10.0)
    v3->set_at(3, 20.0)
    var sd: tensor& = q3->sdpa(k3, v3, false)
    var sdc: tensor& = q3->sdpa(k3, v3, true)
    printf("sdpa at0=%.4f at1=%.4f causal at0=%.4f at1=%.4f\n", sd->at(0), sd->at(1), sdc->at(0), sdc->at(1))
    var x1sh[3]: i4
    x1sh[0] = 1
    x1sh[1] = 1
    x1sh[2] = 6
    var x1raw: tensor& = arange(0.0, 6.0, 1.0, DT_F8)
    var x1d: tensor& = x1raw->reshape(3, x1sh)
    var w1sh[3]: i4
    w1sh[0] = 1
    w1sh[1] = 1
    w1sh[2] = 3
    var w1d: tensor& = ones(3, w1sh, DT_F8)
    var b1sh[1]: i4
    b1sh[0] = 1
    var b1d: tensor& = zeros(1, b1sh, DT_F8)
    var c1d: tensor& = x1d->conv1d(w1d, b1d, 1, 0)
    var p1m: tensor& = x1d->max_pool1d(2, 2, 0)
    var p1a: tensor& = x1d->avg_pool1d(2, 2, 0)
    printf("conv1d at0=%g at3=%g pool1d max2=%g avg2=%.4f\n", c1d->at(0), c1d->at(3), p1m->at(2), p1a->at(2))
    var x2sh[4]: i4
    x2sh[0] = 1
    x2sh[1] = 1
    x2sh[2] = 3
    x2sh[3] = 3
    var x2raw: tensor& = arange(0.0, 9.0, 1.0, DT_F8)
    var x2d: tensor& = x2raw->reshape(4, x2sh)
    var w2sh[4]: i4
    w2sh[0] = 1
    w2sh[1] = 1
    w2sh[2] = 2
    w2sh[3] = 2
    var w2d: tensor& = ones(4, w2sh, DT_F8)
    var b2d: tensor& = zeros(1, b1sh, DT_F8)
    var c2d: tensor& = x2d->conv2d(w2d, b2d, 1, 1, 0, 0)
    var p2m: tensor& = x2d->max_pool2d(2, 2, 1, 1, 0, 0)
    var p2a: tensor& = x2d->avg_pool2d(2, 2, 1, 1, 0, 0)
    printf("conv2d at0=%g at3=%g pool2d max0=%g max3=%g avg0=%.4f avg3=%.4f\n", c2d->at(0), c2d->at(3), p2m->at(0), p2m->at(3), p2a->at(0), p2a->at(3))
    var trm: tensor& = tri(3, 3, 0, DT_F8)
    printf("tri sum=%g at0=%g at1=%g\n", trm->sum_all(), trm->at(0), trm->at(1))
    var xa: tensor& = arange(0.0, 3.0, 1.0, DT_F8)
    var ya: tensor& = arange(0.0, 2.0, 1.0, DT_F8)
    var marr[2]: &
    marr[0] = (xa: &)
    marr[1] = (ya: &)
    var mout[2]: &
    var mgok: bool = meshgrid((marr: &), 2, 0, (mout: &))
    var gx: tensor& = (mout[0]: tensor&)
    var gy: tensor& = (mout[1]: tensor&)
    printf("meshgrid ok=%d gx d0=%d d1=%d at0=%g at5=%g gy at0=%g at5=%g\n", (mgok: i4), gx->dim(0), gx->dim(1), gx->at(0), gx->at(5), gy->at(0), gy->at(5))
    rand_seed(42)
    var ru: tensor& = rand_uniform(2, shp, 0.0, 1.0, DT_F8)
    var rnd: tensor& = rand_normal(2, shp, 0.0, 1.0, DT_F8)
    var ri: tensor& = rand_randint(2, shp, 0, 10, DT_I8)
    var pm: tensor& = permutation(5, DT_I8)
    printf("rand numel=%lld randint numel=%lld perm sum=%g\n", ru->numel, ri->numel, pm->sum_all())
    printf("normal numel=%lld\n", rnd->numel)
    var shf: tensor& = arange(0.0, 6.0, 1.0, DT_F8)
    var shfok: bool = shf->shuffle_()
    printf("shuffle ok=%d sum=%g\n", (shfok: i4), shf->sum_all())
    var svok: bool = b2->save("/tmp/ts_basic.npy")
    var ld: tensor& = ts_load("/tmp/ts_basic.npy")
    printf("save ok=%d load dim0=%d dim1=%d at5=%g\n", (svok: i4), ld->dim(0), ld->dim(1), ld->at(5))
    a->drop()
    b->drop()
    b2->drop()
    c->drop()
    row->drop()
    bc->drop()
    d->drop()
    mm->drop()
    sm->drop()
    mn->drop()
    am->drop()
    ng->drop()
    rl->drop()
    t->drop()
    tc->drop()
    ey->drop()
    ls->drop()
    ab->drop()
    cl->drop()
    gt->drop()
    wh->drop()
    sl->drop()
    r0->drop()
    fl->drop()
    cs->drop()
    ou->drop()
    cat->drop()
    nz->drop()
    gi->drop()
    go->drop()
    sc0->drop()
    ssrc->drop()
    pd->drop()
    ro->drop()
    lsm->drop()
    lr->drop()
    gl->drop()
    tgt->drop()
    mset->drop()
    bct->drop()
    ln->drop()
    dr->drop()
    dr_eval->drop()
    sn->drop()
    cn->drop()
    a2->drop()
    tu->drop()
    tl->drop()
    M->drop()
    Mi->drop()
    bb->drop()
    xx->drop()
    Lc->drop()
    evals->drop()
    evecs->drop()
    Qm->drop()
    Rm->drop()
    bu->drop()
    du->drop()
    bm->drop()
    ones22->drop()
    adm->drop()
    q3->drop()
    k3->drop()
    v3->drop()
    sd->drop()
    sdc->drop()
    x1raw->drop()
    x1d->drop()
    w1d->drop()
    b1d->drop()
    c1d->drop()
    p1m->drop()
    p1a->drop()
    x2raw->drop()
    x2d->drop()
    w2d->drop()
    b2d->drop()
    c2d->drop()
    p2m->drop()
    p2a->drop()
    trm->drop()
    xa->drop()
    ya->drop()
    gx->drop()
    gy->drop()
    ru->drop()
    rnd->drop()
    ri->drop()
    pm->drop()
    shf->drop()
    ld->drop()
    return 0
